name: cut-release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'cart'

jobs:
  # GitHub no longer provides older runners
  #test-legacy:
  #  name: Test functionality on legacy MacOS versions
  #  runs-on: macos-13
  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v4

  #    - name: Test functionality
  #      run: |
  #        ./test.sh

  cut-release:
    name: Cut release
    #needs: test-legacy
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test functionality
        run: |
          ./test.sh

      - name: Get current version
        run: |
          echo version="$(./cart | /usr/bin/tail -1 | /usr/bin/awk '{print $2}')" >> $GITHUB_ENV
          shasum -a 256 ./cart > cart.checksum

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "cart,cart.checksum,docs/README.md,cart.config"
          bodyFile: "changelog.md"
          tag: ${{ env.version }}
          makeLatest: true
          replacesArtifacts: true
          allowUpdates: true
